services:
  - type: web
    name: data-viz-banque-senegal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_DEBUG
        value: "0"
